apiVersion: v1
kind: Service
metadata:
  name: ion-dashboard
spec:
  type: NodePort
  selector:
    app: ion-dashboard
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3001
      nodePort: 30090
